const express = require('express');
//const tokenMid = require('../middlewares/tokens');
const controller = require('../controllers/hedis');
const CommunicationController = require('../controllers/hedis/communications');
const AuthGuard = require('../middleware/auth');
const router = express.Router();

// Get all logs route 
router.post('/getPCP', controller.getPCP);
router.post('/getinsheislist', controller.getinsheislist);
router.post('/getavailabledaily', controller.getavailabledaily);
router.post('/getavailablencompliant', controller.getavailablencompliant);
router.post('/getData', controller.getData);
router.post('/getDaily', controller.getDaily);
router.post('/getNcompliant', controller.getNcompliant);
router.post('/updateValueBP', controller.updateValueBP);
router.post('/updateValue', controller.updateValue);
router.post('/updateStatus', controller.updateStatus);
router.post('/exportexcel', controller.exportexcel);
router.post('/exportdailyexcel', controller.exportdailyexcel);
router.post('/exportncompliantexcel', controller.exportncompliantexcel);
router.post('/outputhedis', controller.outputhedis);
router.post('/printletter', controller.printletter);
router.post('/printdaily', controller.printdaily);
router.post('/printncompliant', controller.printncompliant);
router.post('/checkemail', controller.checkemail);
router.post('/checksms', controller.checksms);
router.post('/sendemail', controller.sendemail);
router.post('/sendsms', controller.sendsms);
router.post('/dailyemail', controller.dailyemail);
router.post('/ncompliantemail', controller.ncompliantemail);
router.post('/getpatientchart', controller.getpatientchart);
router.post('/getpatientnotes', controller.getpatientnotes);
router.post('/gethedisdashdata', controller.gethedisdashdata);
router.post('/writenotes', controller.writenotes);
router.post('/getnotes', controller.getnotes);
router.post('/updatenote', controller.updatenote);
router.post('/deletenote', controller.deletenote);
router.post('/getallnotes', controller.getallnotes);
router.post('/getchartforallnotes', controller.getchartforallnotes);
router.post('/getptinfonotes', controller.getptinfonotes);
router.post('/chosenHedisitem', controller.chosenHedisitem);
router.post('/updatevisitdate', controller.updatevisitdate);
router.post('/monthreport', controller.monthreport);
router.post('/monthemail', controller.monthemail);
router.post('/setmonthdata', controller.setmonthdata);
router.post('/setmonthdataptstatus', controller.setmonthdataptstatus);
router.post('/getmonthdata', controller.getmonthdata);
router.post('/getmonthdataptstatus', controller.getmonthdataptstatus);
router.post('/gethedispopulation', controller.gethedispopulation);
router.post('/getmactionlog', controller.getmactionlog);
router.post('/getractionlog', controller.getractionlog);
router.post('/updatereported', controller.updatereported);
router.post('/chosenreported', controller.chosenreported);
router.post('/conciergereport', controller.conciergereport);
router.post('/smscredit', controller.smscredit);
router.post('/setsmscounts', controller.setsmscounts);
router.post('/gethedisreport', controller.gethedisreport);
router.post('/getaccessdetail', controller.getaccessdetail);
router.post('/getPTsbyquery', controller.getPTsbyquery);
router.post('/outputretro', controller.outputretro);
router.post('/getPatient', controller.getPatient);

router.post('/communications/checkcalltime', AuthGuard, CommunicationController.checkcalltime);
router.post('/communications/getcalltoken', AuthGuard, CommunicationController.getcalltoken);
router.post('/communications/gettingtwiliologlist', AuthGuard, CommunicationController.gettingtwiliologlist);
router.post('/communications/setcallcounts', AuthGuard, CommunicationController.setcallcounts);

module.exports = router;